### ISSUE TITLE
Estimationの奴

### ISSUE THREAD

**Issue by kojitaniguchi** [Watayo/PlanCheck_web#7]
### 1.カラム名を text から変更する
- カラム名
https://github.com/Watayo/PlanCheck_web/blob/e0cbc617c6cedf9bc843d153cf110367ad68aee7/db/migrate/20200302060846_create__estimations.rb#L4

- アンダーバーを一本にする `/20200302060846_create__estimations.rb` → `/20200302060846_create_estimations.rb`
https://github.com/Watayo/PlanCheck_web/blob/master/db/migrate/20200302060846_create__estimations.rb

### 2. create に変える
```ruby
  register_task.create_task_scale.create_estimation(
    estimation_text: @scale_text,
    img: @scale_img,
    estimation_comment: params[:scale_comment]
  )
```

### 3.これを消す
https://github.com/Watayo/PlanCheck_web/blob/e0cbc617c6cedf9bc843d153cf110367ad68aee7/app.rb#L205-L208

**Comment by Watayo** [comment]
ありがとうございます。
# 今日の予定
- 修正（〜１５：００）
- FBもらいつつLINEBot（〜１８：００）
- FBからの修正

**Comment by kojitaniguchi** [comment]
出来たら教えて〜
